### ISSUE TITLE
fn_dry parsing issue

### ISSUE THREAD

**Issue by amorosc1** [amashadihossein/dpbuild#2]
When initializing a new daap, fn_dry does not correctly parse bucket_name unless it is the last input to the board_params_set_s3 function. 

This works (returns character):
`board_params_set_dried  <- fn_dry(board_params_set_s3(board_alias = "s3_test", region = "us-east-1", bucket_name = "bucket-name"))`

This does not (returns character vector): 
`board_params_set_dried  <- fn_dry(board_params_set_s3(board_alias = "s3_test", bucket_name = "bucket-name", region = "us-east-1"))`

**Comment by camorosi** [comment]
Update: this appears to be due to line wrapping/not correctly handling newline characters, rather than order of input parameters.
