### ISSUE TITLE
folder-check at dp_clone

### ISSUE THREAD

**Issue by amashadihossein** [amashadihossein/dpbuild#26]
`input_folder` and `output` are folders that are needed for building data products and constructed at `dp_init` but in `.gitignore` and hence not on repo. When project is cloned, it is useful to ensure these two necessary empty folders are established within the project, otherwise the user has to manually do that.

**Comment by sbohora** [comment]
I added following codes to establish the "input_files" and "output_files" folders within `tryCatch()` block in `dp_clone()`

```r
input_output_directories <- c("input_files", "output_files")

for (dir in input_output_directories){
    if(!fs::dir_exists(dir)){
        fs::dir_create(dir)
     }
}
```

@amashadihossein @camorosi

**Comment by amashadihossein** [comment]
addressed
